'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { supabase } from '@/lib/supabase';

type Workshop = {
  workshop_id: string;
  title: string;
  code: string;
};

type Assignment = {
  assignment_id: string;
  title: string;
  created_at: string; // Supabase returns string timestamps
};

export default function ClassDetail() {
  const params = useParams();
  const classId = params.classId as string;
  
  const [classData, setClassData] = useState<Workshop | null>(null);
  const [quizzes, setQuizzes] = useState<Assignment[]>([]);
  const [students, setStudents] = useState<any[]>([]); // Enrollments
  const [newQuizTitle, setNewQuizTitle] = useState('');
  const [newStudentId, setNewStudentId] = useState(''); // For enrolling
  const [newStudentName, setNewStudentName] = useState(''); // For creating new student
  const [showNameInput, setShowNameInput] = useState(false);
  const [activeTab, setActiveTab] = useState<'quizzes' | 'students'>('quizzes');
  const [loading, setLoading] = useState(true);

  const fetchClass = async () => {
    const { data, error } = await supabase
      .from('workshops')
      .select('*')
      .eq('workshop_id', classId)
      .single();
    
    if (error) console.error(error);
    else setClassData(data);
    setLoading(false);
  };

  const fetchQuizzes = async () => {
    const { data, error } = await supabase
      .from('assignments')
      .select('*')
      .eq('workshop_id', classId)
      .eq('assignment_type', 'assignment')
      .order('title');

    if (error) console.error(error);
    else setQuizzes(data || []);
  };

  const fetchStudents = async () => {
    // Fetch enrollments and join profiles table to get the name
    const { data, error } = await supabase
      .from('enrollments')
      .select('*, profiles(name)')
      .eq('workshop_id', classId);

    if (error) console.error(error);
    else setStudents(data || []);
  };

  useEffect(() => {
    if (classId) {
      fetchClass();
      fetchQuizzes();
      fetchStudents();
    }
  }, [classId]);

  const handleEnrolStudent = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newStudentId.trim()) return;

    // 1. Check if student exists in profiles
    const { data: student, error: fetchError } = await supabase
      .from('profiles')
      .select('*')
      .eq('id', newStudentId)
      .single();

    if (!student) {
      alert('Student not found. Ensure the student has registered an account and provide their valid User UUID.');
      return;
    }

    // 2. Create Enrollment
    const { error: enrolError } = await supabase
      .from('enrollments')
      .insert([{ workshop_id: classId, student_id: newStudentId }]);

    if (enrolError) {
      alert(`Error enrolling: ${enrolError.message}`); // Likely duplicate key if already enrolled
    } else {
      alert('Student enrolled successfully!');
      setNewStudentId('');
      fetchStudents();
    }
  };

  const handleCreateQuiz = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newQuizTitle.trim()) return;

    // assignment_id is generated by default (uuid)
    const { error } = await supabase
      .from('assignments')
      .insert([
        {
          workshop_id: classId,
          title: newQuizTitle,
          assignment_type: 'assignment',
          points: 100, // Default
          due_date: new Date().toISOString() // Placeholder date
        }
      ]);

    if (error) {
      alert(`Failed to create quiz: ${error.message}`);
    } else {
      setNewQuizTitle('');
      fetchQuizzes();
    }
  };

  if (loading) return <div className="p-8 text-center text-gray-500">Loading class details...</div>;
  if (!classData) return <div className="p-8 text-center text-red-500">Class not found.</div>;

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b shadow-sm">
        <div className="max-w-7xl mx-auto px-4 py-6">
          <Link href="/" className="text-sm text-indigo-600 hover:text-indigo-800 mb-2 inline-block">
            &larr; Back to Dashboard
          </Link>
          <h1 className="text-3xl font-bold text-gray-900">{classData.title}</h1>
          <p className="text-gray-500">{classData.code}</p>

          {/* Tabs */}
          <div className="flex gap-4 mt-6 border-b border-gray-200">
            <button
              onClick={() => setActiveTab('quizzes')}
              className={`pb-3 px-4 text-sm font-medium transition-colors border-b-2 ${
                activeTab === 'quizzes' 
                  ? 'border-indigo-600 text-indigo-600 bg-indigo-50' 
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-gray-50'
              }`}
            >
              Assignments (Quizzes)
            </button>
            <button
              onClick={() => setActiveTab('students')}
              className={`pb-3 px-4 text-sm font-medium transition-colors border-b-2 ${
                activeTab === 'students' 
                  ? 'border-indigo-600 text-indigo-600 bg-indigo-50' 
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-gray-50'
              }`}
            >
              Students (Roster)
            </button>
          </div>
        </div>
      </div>

      {/* Content Area */}
      <main className="max-w-7xl mx-auto px-4 py-8">
        {activeTab === 'quizzes' && (
          <div className="bg-white p-6 rounded-lg shadow-sm border space-y-6">
            <div className="flex justify-between items-end border-b pb-6">
              <h2 className="text-xl font-semibold text-gray-800">Assigned Quizzes</h2>
              <form onSubmit={handleCreateQuiz} className="flex gap-2">
                <input
                  type="text"
                  value={newQuizTitle}
                  onChange={(e) => setNewQuizTitle(e.target.value)}
                  placeholder="New Quiz Title"
                  className="border rounded px-3 py-1 text-sm w-64 placeholder:text-gray-500 text-gray-900"
                  required
                />
                <button type="submit" className="bg-indigo-600 text-white px-4 py-1 rounded hover:bg-indigo-700 text-sm">
                  Create
                </button>
              </form>
            </div>

            {quizzes.length === 0 ? (
              <div className="text-center py-12 text-gray-400 bg-gray-50 rounded border-2 border-dashed">
                No quizzes created yet.
              </div>
            ) : (
              <div className="grid grid-cols-1 gap-4">
                {quizzes.map((quiz) => (
                  <Link 
                    key={quiz.assignment_id} 
                    href={`/classes/${classId}/quizzes/${quiz.assignment_id}`}
                    className="block border p-4 rounded-lg hover:border-indigo-300 hover:bg-indigo-50 transition"
                  >
                    <div className="flex justify-between items-center">
                      <h3 className="font-semibold text-lg text-gray-900">{quiz.title}</h3>
                    </div>
                  </Link>
                ))}
              </div>
            )}
          </div>
        )}

        {activeTab === 'students' && (
          <div className="bg-white p-6 rounded-lg shadow-sm border space-y-6">
            <div className="flex justify-between items-end border-b pb-6">
              <h2 className="text-xl font-semibold text-gray-800">Class Roster ({students.length})</h2>
              
              <form onSubmit={handleEnrolStudent} className="flex gap-2 items-end">
                <div>
                  <input
                    type="text"
                    value={newStudentId}
                    onChange={(e) => setNewStudentId(e.target.value)}
                    placeholder="Student UUID"
                    className="border rounded px-3 py-1 text-sm w-64 placeholder:text-gray-500 text-gray-900"
                    required
                  />
                </div>
                <button type="submit" className="bg-green-600 text-white px-4 py-1 rounded hover:bg-green-700 text-sm">
                  Enrol
                </button>
              </form>
            </div>
            
            {students.length === 0 ? (
              <div className="text-center py-12 text-gray-400 bg-gray-50 rounded border-2 border-dashed">
                No students enrolled.
              </div>
            ) : (
              <div className="overflow-hidden border rounded-lg">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Student ID (UUID)</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {students.map((s) => (
                      <tr key={s.id}>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                          {s.profiles?.name || 'Unknown Name'}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {s.student_id}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  );
}
